---
title: "`r params$glds` Microarray Data Processing Report"
author: "NASA GeneLab Project"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    self_contained: true
params:
  glds:
    label: "Enter GLDS Accession #"
    input: text
    value: "GLDS-44"
    width: "400"
  organism:
    label: "Select Organism"
    input: select
    choices: ["Homo sapiens","Mus musculus","Rattus norvegicus","Danio rerio","Drosophila melanogaster","Caenorhabditis elegans","Saccharomyces cerevisiae","Arabidopsis thaliana","Escherichia coli","Bacillus subtilis"]
    value: "Arabidopsis thaliana"
    width: "400"
  format:
    label: "Microarray Data Format"
    input: select
    choices: ["Affymetrix Expression","Affymetrix ST", "NimbleGen", "Illumina BeadChip", "Agilent","Agilent GenePix"]
    value: "Affymetrix Expression"
    width: "400"
  primary:
    label: "Primary Annotation Keytype"
    choices: [REFSEQ,ENSEMBL,GENBANK,SYMBOL,ENTREZID,TAIR,ORF,SGD]
    input: select
    width: "400"
    value: TAIR
  datafiles:
    label: "Select Raw Data Files"
    input: file
    multiple: TRUE
    buttonLabel: "Browse..."
    placeholder: "No files selected"
    value: NULL
    width: "400"
  probefile:
    label: "Select Probe Annotation File"
    input: file
    multiple: FALSE
    buttonLabel: "Browse..."
    placeholder: "No file selected"
    value: NULL
    width: "400"
  isafile:
    label: "Select ISA Metadata File"
    input: file
    multiple: FALSE
    buttonLabel: "Browse..."
    placeholder: "No file selected"
    value: NULL
    width: "400"

knit: (function(inputFile, encoding) { 
          out_path<-rmarkdown::render(inputFile,
                        encoding=encoding, 
                        params='ask',
                        envir=new.env(),
                        output_file="summary_report.html")})

---

```{r setup, include=FALSE}
### Requires R (version "4.0") or higher
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
opt<-as.list(params)
workdir<-getwd()


## Code to send output document to browser directly and change output directory to study folder. 
# knit: (function(inputFile, encoding) { 
#           out_path <- rmarkdown::render(inputFile,
#                         encoding=encoding, 
#                         params='ask',
#                         envir=new.env(),
#                         output_dir="`r dirname(params$isafile$datapath)`",
#                         output_file="summary_report.html")})
#           utils::browseURL(out_path)
```

```{r manual_entry, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
### Set Parameters Manually. 
### Change chunk options to eval=TRUE to overide YAML params

workdir <- "/Users/hfogle/R_Docs/one_channel_arrays"    # For testing
which_assay <- 1 # for studies with multiple two-channel microarrays
opt <- list()

opt$glds <-"GLDS-225"
opt$organism <- "Rattus norvegicus"
opt$format <- "Affymetrix ST"
opt$model <- "Group Contrast"
opt$estimation <- "Max IQR"
opt$primary <- "REFSEQ"
opt$filter_nonexpressed <- TRUE
opt$filter_control <- TRUE
opt$filter_nonannotated <- TRUE
opt$datafiles$name <- list.files(file.path(workdir,"demo_dataset",opt$glds,"00-RawData"),pattern = c("*CEL"),full.names = FALSE )
opt$datafiles$datapath <- list.files(file.path(workdir,"demo_dataset",opt$glds,"00-RawData"),pattern = c("*CEL"),full.names = TRUE )
opt$probefile$name <- list.files(file.path(workdir,"demo_dataset",opt$glds,"Metadata"),pattern = "*db.tar.gz",full.names = FALSE )
opt$probefile$datapath <- list.files(file.path(workdir,"demo_dataset",opt$glds,"Metadata"),pattern = "*db.tar.gz",full.names = TRUE )
opt$isafile$name <- list.files(file.path(workdir,"demo_dataset",opt$glds,"Metadata"),pattern = "*ISA.zip",full.names = FALSE )
opt$isafile$datapath <- list.files(file.path(workdir,"demo_dataset",opt$glds,"Metadata"),pattern = "*ISA.zip",full.names = TRUE )

```
## Input Parameters
```{r warning=FALSE}
### Display report options selected
source("microarray_functions.R")
all_targets<-buildTargets(opt)
if (length(all_targets) == 1){
  targets <- all_targets[[1]]
}else{
  targets <- all_targets[[which_assay]]
}
opt$model <- "Group Contrast"
opt$estimation <- "Max IQR"

opt$filter_nonexpressed <- TRUE
opt$filter_control <- TRUE
opt$filter_nonannotated <- TRUE
str(opt)
```

```{r eval=(grepl("\\.annotation.tar.gz$", opt[["probefile"]][["name"]])), include=FALSE}
### Get annotations for probe ids
database <- sub('\\.tar.gz$', '', opt[["probefile"]][["name"]]) 
if(!require(database, character.only=TRUE)) {
  BiocManager::install(database, ask = FALSE)
}
  install.packages(opt[["probefile"]][["datapath"]],repos = NULL)
  library(database, character.only=TRUE)
```

```{r}
### Selects appropriate package for plots
if ((opt$format == "Affymetrix Expression") | (opt$format == "Affymetrix ST") | (opt$format == "NimbleGen")){
  plots <- "OLIGO"
}else if((opt$format == "Illumina BeadChip") | (opt$format == "Agilent") | (opt$format == "Agilent GenePix")){
  plots <- "LIMMA"
}else {
  plots <- NULL
}

  
datapaths<-opt[["datafiles"]][["datapath"]]
datanames<-opt[["datafiles"]][["name"]]
```

## Study Sample Grouping
```{r}
 ### Parse ISAtab metadata file and extract sample and factor data

  
 
  DT::datatable(targets$t1)
```

## Load Raw Data
```{r}
for (file in opt$datafiles$datapath){
    if (grepl("\\.gz$", file)) {
      R.utils::gunzip(filename = file, remove = TRUE)
      opt$datafiles$datapath<-list.files(dir(opt$datafiles$datapath))}
}
rm(file)
```
```{r eval=(opt$format == "Affymetrix Expression"),echo=(opt$format == "Affymetrix Expression"), include=FALSE}

try({raw <- oligo::read.celfiles(datapaths)})
if (opt$organism == "Rattus norvegicus"){
  try({raw <- oligo::read.celfiles(datapaths, pkgname=database)})
}

```
```{r eval=(opt$format == "Affymetrix ST"),echo=(opt$format == "Affymetrix ST"), include=FALSE}
raw <- oligo::read.celfiles(datapaths)
```
```{r eval=(opt$format == "Agilent GenePix"),echo=(opt$format == "Agilent GenePix"), include=FALSE}
raw<-limma::read.maimages(targets$t1$FileName, source="genepix", path=dirname(datapaths[1]),wt.fun=wtflags(weight=0,cutoff=-50), green.only=TRUE, names = targets$t1$SampleName)
```
```{r eval=(opt$format == "Agilent"),echo=(opt$format == "Agilent"), include=FALSE}
raw<-limma::read.maimages(targets$t1$FileName, source="agilent", path=dirname(datapaths[1]), green.only=TRUE, targets$t1$SampleName)
```
```{r eval=(opt$format == "Nimblegen"),echo=(opt$format == "Nimblegen"), include=FALSE}
options(try.outFile = stdout()) 
try(raw <- oligo::read.xysfiles(datapaths))
try(raw <- HELP::readPairs(datapaths))
```
```{r eval=(opt$format == "Illumina"),echo=(opt$format == "Illumina"), include=FALSE}
options(try.outFile = stdout()) 
try(raw <- read.ilmn(datanames, opt[["probefile"]][["name"]],path=dirname(datapaths[1]),ctrpath=dirname(datapaths[1]),probeid="Probe",annotation=c("TargetID", "SYMBOL"),expr="AVG_Signal",sep="\t", quote="\""))
try(raw <- read.idat(datapaths,opt[["probefile"]][["name"]],annotation = c("RefSeq_ID","Symbol","Entrez_Gene_ID","Definition"),tolerance = 0L))
```
```{r}
# if (grepl("\\.db.annotation.tar.gz$", opt$probefile$name)){
#   database <- sub('\\.annotation.tar.gz$', '', opt$probefile$name)
#   annotation(raw)<-database
# }
show(raw)
```

```{r include=FALSE}

### If data imports properly, start building ouput files

dir.create(file.path(workdir,"Processed_Data"), showWarnings = FALSE)
dir.create(file.path(workdir,"Processed_Data",opt$glds), showWarnings = FALSE)
dir.create(file.path(workdir,"Processed_Data",opt$glds,"00-RawData"), showWarnings = FALSE)
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData")
file.copy(from = datapaths, to = file.path(path,datanames), overwrite = FALSE, recursive = FALSE, copy.mode = FALSE)
rm(path)
```

## Raw Data MA Plots
```{r eval=(plots == "OLIGO"), echo=(plots == "OLIGO")}
 
dir.create(file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports"), showWarnings = FALSE)
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)
count <- dim(targets$t1)[1]
printrows <- ceiling(count/4)
width <- 2000
png(filename = file.path(path,"rawPlotMA.png"), width = width, height = ceiling(width/4)*printrows)
par(mfrow = c(printrows,4),mar=c(5,5,5,5))
for (i in 1:count){
  oligo::MAplot(raw, pairs=FALSE, which=count)
  }
invisible(dev.off())
for (i in 1:count){
  oligo::MAplot(raw, pairs=FALSE, which=count)
  }

rm(path,printrows,width,count,i)
```
```{r eval=(plots == "LIMMA"), echo=(plots == "LIMMA")}
 
dir.create(file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports"), showWarnings = FALSE)
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)
count <- dim(targets$t1)[1]
printrows <- ceiling(count/4)
width <- 2000
png(filename = file.path(path,"rawPlotMA.png"), width = width, height = ceiling(width/4)*printrows)
par(mfrow = c(printrows,4),mar=c(5,5,5,5))
for (i in 1:count){
  plotMD(raw, column = count, xlab = "Average log-expression", ylab = "log-fold-change", main = colnames(raw)[count])
  }
invisible(dev.off())
for (i in 1:count){
  plotMD(raw, column = count, xlab = "Average log-expression", ylab = "log-fold-change", main = colnames(raw)[count])
  }

rm(path,printrows,width,count,i)
```

```{r include=FALSE}
# Create Array Info File
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)
write.table(as.data.frame(opt[1:(length(opt)-3)]),file = "arrayInfo.txt", quote = FALSE)
```

## Raw Data Density Plot
```{r eval=(plots == "OLIGO"), echo=(plots == "OLIGO")}
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)
if (opt$format == "Affymetrix ST"){
  oligo::hist(raw, main = "Raw Data Density Distribution", target="probeset")
  png(file = "rawDensityDistributions.png")
  oligo::hist(raw, main = "Raw Data Density Distribution", target="probeset")
  invisible(dev.off())
  
}else{
  oligo::hist(raw, main = "Raw Data Density Distribution")
  png(file = "rawDensityDistributions.png")
  oligo::hist(raw, main = "Raw Data Density Distribution")
  invisible(dev.off())
  
}

```
```{r eval=(plots == "LIMMA"), echo=(plots == "LIMMA")}
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)

plotDensities(raw, legend = FALSE)
png(file = "rawDensityDistributions.png")
plotDensities(raw, legend = FALSE)
invisible(dev.off())
  
```
## Raw Data Box Plot
```{r eval=(plots == "OLIGO"), echo=(plots == "OLIGO")}

path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)

if (opt$format == "Affymetrix ST"){
png(filename = file.path(path,"rawBoxplot.png"), width = 1000, height = 1000)
  par(mar=c(30,5,5,5))
oligo::boxplot(raw,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Raw Data Log2 Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities", target="probeset")
invisible(dev.off())
  
oligo::boxplot(raw,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Raw Data Log2 Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities", target="probeset")
  
}else{
png(filename = file.path(path,"rawBoxplot.png"), width = 1000, height = 1000)
  par(mar=c(30,5,5,5))
oligo::boxplot(raw,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Raw Data Log2 Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities")
invisible(dev.off())
  
oligo::boxplot(raw,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Raw Data Log2 Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities")
  
}
```

```{r eval=(plots == "LIMMA"), echo=(plots == "LIMMA")}

path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)

png(filename = file.path(path,"rawBoxplot.png"), width = 1000, height = 1000)
  par(mar=c(30,5,5,5))
boxplot(data.frame(log2(as.matrix(raw))),main="Raw Data Log2 Intensities", las=2,outline=FALSE)
invisible(dev.off())
  
boxplot(data.frame(log2(as.matrix(raw))),main="Raw Data Log2 Intensities", las=2,outline=FALSE)

```

```{r include=FALSE}

########## Create Checksum file
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)
checksums <- tools::md5sum(file.path(workdir,"Processed_Data",opt$glds,"00-RawData", opt$datafiles$name))
names(checksums) <- datanames
write.table(checksums, "md5sum.txt",quote = FALSE)
rm(path,checksums)
```
## Raw Data PCA Plot
```{r}
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","QC_Repports")
setwd(path)
########## Create Raw PCA Plots
library(ggplot2)
try(exp_raw <- log2(exprs(raw)))
try(exp_raw <- log2(as.matrix(raw)))
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)
try({PCA_raw <- prcomp(t(exp_raw), scale. = TRUE)}) # scaling will fail for low replicates
percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])
dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2], Group = targets$t1$Group)
PCA_plot <- ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(colour = Group)) +
  ggtitle("Raw Data PCA Plot of log2 Expression") +
  xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
  ylab(paste0("PC2, VarExp: ", percentVar[2], "%"))
png(filename = file.path(path,"rawPCA.png"))
plot(PCA_plot)
dev.off()
plot(PCA_plot)
rm(exp_raw, PCA_raw,dataGG, PCA_plot,percentVar,sd_ratio)
```

## Array Spot Log Intensity Images
```{r eval=(plots == "OLIGO"),echo=(plots == "OLIGO")}
########## Create Array Image Plots
dir.create(file.path(workdir,"Processed_Data",opt$glds,"00-RawData","Images"), showWarnings = FALSE)
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","Images")
setwd(path)
count <- dim(targets$t1)[1]
printrows <- ceiling(count/4)
width <- 2000
png(file = "images.png", width = width, height = ceiling(width/4)*printrows)
par(mfrow = c(printrows,4),mar=c(5,5,5,5))
for (i in 1:count){
  oligo::image(raw, transfo=log2, which=i)
  }
invisible(dev.off())
for (i in 1:count){
  oligo::image(raw, transfo=log2,which=i)
  }
rm(path,printrows,width,count,i)
```
```{r eval=(plots == "LIMMA"),echo=(plots == "LIMMA")}
########## Create Array Image Plots
dir.create(file.path(workdir,"Processed_Data",opt$glds,"00-RawData","Images"), showWarnings = FALSE)
path <- file.path(workdir,"Processed_Data",opt$glds,"00-RawData","Images")
setwd(path)
count <- dim(targets$t1)[1]
printrows <- ceiling(count/4)
width <- 2000
if (opt$format == "Agilent"){
  r <- raw$genes$Row
  c <- raw$genes$Col
  nr <- max(r)
  nc <- max(c)
  y <- rep(NA,nr*nc)
  i <- (r-1)*nc+c
  y[i] <- log2(raw$Eb[,1])
  raw$printer <- list(ngrid.r=1,ngrid.c=1,nspot.r=nr,nspot.c=nc) 
}

png(file = "images.png", width = width, height = ceiling(width/4)*printrows)
par(mfrow = c(printrows,4),mar=c(5,5,5,5))
for (ind in 1:count){
  imageplot(y,raw$printer, main=colnames(raw$Eb)[i])
  }
invisible(dev.off())
for (ind in 1:count){
  imageplot(y,raw$printer, main=colnames(raw$Eb)[i])
  }
rm(path,printrows,width,count,i)
```
## Background Correction and Normalizations
```{r eval=(opt$format == "Affymetrix Expression"),echo=(opt$format == "Affymetrix Expression"), include=FALSE}
data <- oligo::rma(raw, normalize = TRUE, background = TRUE)
data.bgonly <- oligo::rma(raw, normalize = FALSE, background = TRUE)
cat("RMA background correction and quantile normalization performed.")
```
```{r eval=(opt$format == "Affymetrix ST"),echo=(opt$format == "Affymetrix ST"), include=FALSE}
data <- oligo::rma(raw, target = "core", background=TRUE, normalize=TRUE)
data.bgonly <- oligo::rma(raw, target = "core", background=TRUE, normalize=FALSE)
cat("RMA background correction and quantile normalization performed with gene level summarization.")
```
```{r eval=(opt$format == "Agilent"),echo=(opt$format == "Agilent"), include=FALSE}
data <- backgroundCorrect(raw, method="normexp", offset=50)
data.bgonly <- backgroundCorrect(raw, method="normexp", offset=50)
data <- normalizeBetweenArrays(data, method="quantile")
cat("Normexp background correction and Quantile normalization performed.")
```


```{r eval=(plots == "OLIGO"),echo=(plots == "OLIGO")}
### Begin tracking feature annotation stats
annotation_stats <- list()
annotation_stats$total_features <- dim(data@featureData@data)[1]
```
```{r eval=(plots == "LIMMA"),echo=(plots == "LIMMA")}
### Begin tracking feature annotation stats
annotation_stats <- list()
annotation_stats$total_features <- dim(data$genes)[1]
```
```{r eval=(opt$format == "Agilent"),echo=(opt$format == "Agilent")}
###  Write out the expression values
dir.create(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData"), showWarnings = FALSE)
setwd(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData"))
data <- data[data$genes$ControlType == 0,]

expression<-cbind(data$genes$ProbeName,expression)
write.csv(expression,"normalized.txt",quote=FALSE, append=FALSE)

```
```{r eval=(plots == "OLIGO"),echo=(plots == "OLIGO")}
###  Write out the expression values
dir.create(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData"), showWarnings = FALSE)
setwd(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData"))
expression <- data.frame(Biobase::exprs(data))
write.csv(expression,"normalized.txt",quote=FALSE, append=FALSE)

```

```{r eval=(plots == "OLIGO"),echo=(plots == "OLIGO")}
### Try probe database first
keytype<-"PROBEID"
keys<-rownames(expression)
annotation(data)<-database
```


```{r}
### Get organism annotation package
organism_table <- read.csv(file = file.path(getwd(),"organisms.csv"), header = TRUE, stringsAsFactors = FALSE)
ann.dbi <- organism_table$annotations[organism_table$species == opt$organism] # Organism specific gene annotation database
ann.dbi=as.character(ann.dbi)
if(!require(ann.dbi, character.only=TRUE)) {
  BiocManager::install(ann.dbi, ask = FALSE)
  library(ann.dbi, character.only=TRUE)
}
```


```{r eval=(opt$format == "Agilent"),echo=(opt$format == "Agilent")}
# probedata <- Biobase::read.AnnotatedDataFrame(opt$probefile$datapath, sep = "\t", header = TRUE, fill = TRUE, quote = "", stringsAsFactors = FALSE, varMetadata.char="#") 
database<-ann.dbi
keytype<-opt$primary
keys<-data$genes$SystematicName
```

```{r include=FALSE}
### Map assay database annotations
annotation <- data.frame(REFSEQ=mapIds(eval(parse(text = database),env=.GlobalEnv),keys = keys,keytype = keytype, column = "REFSEQ",multiVals = "first"))

try(annotation$ENSEMBL<-mapIds(eval(parse(text = database),env=.GlobalEnv),keys = keys,keytype = keytype, column = "ENSEMBL",multiVals = "first"))
try(annotation$SYMBOL<-mapIds(eval(parse(text = database),env=.GlobalEnv),keys = keys,keytype = keytype, column = "SYMBOL",multiVals = "first"))
try(annotation$DESCRIPTION<-mapIds(eval(parse(text = database),env=.GlobalEnv),keys = keys,keytype = keytype, column = "GENENAME",multiVals = "first"))
try(annotation$ENTREZID<-mapIds(eval(parse(text = database),env=.GlobalEnv),keys = keys,keytype = keytype, column = "ENTREZID",multiVals = "first"))
try(annotation$TAIR<-mapIds(eval(parse(text = database),env=.GlobalEnv),keys = keys,keytype = keytype, column = "TAIR",multiVals = "first"))
try(annotation$GOSLIM_ID<-mapIds(eval(parse(text = database),env=.GlobalEnv),keys = keys,keytype = keytype, column = "GO",multiVals = "first"))


#annotation<- select(eval(parse(text = database)), keys=keys, columns = c("REFSEQ","ENSEMBL","SYMBOL","GENENAME","ENTREZID","GO"),
#       keytype=keytype)

# if(! "ENSEBML" %in% colnames(annotation))
# {
#   if (opt$organism == "Arabidopsis thaliana"){
#    mart <- biomaRt::useMart(biomart = "plants_mart", host = "plants.ensembl.org", dataset = "athaliana_eg_gene")
#    filters <- "tair_symbol"
#   theIDs <- biomaRt::getBM(attributes="ensembl_gene_id", filters= filters,
# values=annotation$TAIR, mart=mart,uniqueRows=TRUE) 
#   }
# rm(mart,filters,theIDs)
# }

### Map STRING annotations
try({
string_db <- STRINGdb::STRINGdb$new( version="11", species=organism_table$taxon[organism_table$species == opt$organism],score_threshold=0)
string_map<-string_db$map(annotation,"REFSEQ",removeUnmappedRows = FALSE, takeFirst = TRUE)
annotation$STRING_ID <- string_map$STRING_id
rm(string_map,string_db)
})
rm(keytype,keys,database)
```
```{r}
### Generate normalized annotated expression text file
setwd(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData"))
expression <- cbind(annotation,expression)
write.csv(expression,"normalized-annotated.txt",quote=FALSE, append = FALSE)

```
```{r eval=(plots == "OLIGO"),echo=(plots == "OLIGO")}
### Rename assay samples with ISAtab sample names
index<-sapply(targets$t1$SampleName,function(x){grep(x,sampleNames(data))})
sampleNames(data)<-targets$t1$SampleName[order(index)]
### Sort assay data to be in same order as ISAtab metadata
targets$t1 <- targets$t1[order(index),]
targets$t2 <- targets$t2[order(index),]
targets$t3 <- targets$t3[order(index),]


rm(index)
```
```{r eval=(plots == "OLIGO"),echo=(plots == "OLIGO"),message=FALSE, warning=FALSE}
### Annotate the expression set object and save as a file
setwd(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData"))
fData(data)<-annotation
save(data,file = "normalized-annotated.rda")
fData(data.bgonly)<-annotation
save(data.bgonly,file = "uncorrected-annotated.rda")
```

```{r eval=(plots == "LIMMA"),echo=(plots == "LIMMA"),message=FALSE, warning=FALSE}
### Annotate the expression set object and save as a file
setwd(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData"))
data$annotation<-annotation
save(data,file = "normalized-annotated.rda")

```
## Normalized Data MA Plot
```{r eval=(plots == "LIMMA"), echo=(plots == "LIMMA")}
 
  dir.create(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports"), showWarnings = FALSE)
  path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
  setwd(path)
count <- dim(targets$t1)[1]
printrows <- ceiling(count/4)
width <- 2000
png(filename = file.path(path,"normPlotMA.png"), width = width, height = ceiling(width/4)*printrows)
par(mfrow = c(printrows,4),mar=c(5,5,5,5))
for (i in 1:count){
  plotMD(data, column = count, xlab = "Average log-expression", ylab = "log-fold-change", main = colnames(data)[count])
  }
invisible(dev.off())
for (i in 1:count){
  plotMD(data, column = count, xlab = "Average log-expression", ylab = "log-fold-change", main = colnames(data)[count])
  }

rm(path,printrows,width,count,i)
```

```{r eval=(plots == "OLIGO"), echo=(plots == "OLIGO")}

  dir.create(file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports"), showWarnings = FALSE)
  path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
  setwd(path)
  count <- dim(targets$t1)[1]
  
printrows <- ceiling(count/4)
width <- 2000
png(filename = file.path(path,"normPlotMA.png"), width = width, height = ceiling(width/4)*printrows)
par(mfrow = c(printrows,4),mar=c(5,5,5,5))
for (i in 1:count){
  oligo::MAplot(data, pairs=FALSE, which=i)
  }
invisible(dev.off())
for (i in 1:count){
  oligo::MAplot(data, pairs=FALSE, which=i)
  }
rm(printrows,count,width,i)
```
## Normalized Density Plot
```{r eval=(plots == "OLIGO"), echo=(plots == "OLIGO"), message=FALSE, warning=FALSE}
  path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
  setwd(path)
  count <- dim(targets$t1)[1]
  ########## Create Expression Density Plots
png(filename = file.path(path,"normDensityDistributions.png"))
oligo::hist(data,transfo=log2, nsample=10000,main=paste0(opt$glds," Normalized Intensity Distributions"),xlab="log2 Intentisty",ylab="Density",col=rainbow(count),lty=1)
legend("topright",legend=targets$t1$SampleName,fill = rainbow(count))
invisible(dev.off())

oligo::hist(data,transfo=log2, nsample=10000,main=paste0(opt$glds," Normalized Intensity Distributions"),xlab="log2 Intentisty",ylab="Density",col=rainbow(count),lty=1)
legend("topright",legend=targets$t1$SampleName,fill = rainbow(count))
rm(count,path)
```

```{r eval=(plots == "LIMMA"), echo=(plots == "LIMMA")}
  path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
  setwd(path)

plotDensities(data, legend = FALSE)
png(file = "normDensityDistributions.png")
plotDensities(data, legend = FALSE)
invisible(dev.off())
  
```
## Normalized Box Plot
```{r eval=(plots == "OLIGO"), echo=(plots == "OLIGO"), message=FALSE, warning=FALSE}
   ########## Create Normalized Boxplots
  path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
  setwd(path)

  png(filename = file.path(path,"normBoxplot.png"), width = 1000, height = 1000)
  par(mar=c(30,5,5,5))
  oligo::boxplot(data,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Normalized Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities")
  invisible(dev.off())
  
  oligo::boxplot(data,which="pm",transfo=log2, nsample=10000,main=paste0(opt$glds," Normalized Intensities"), las=2,outline=FALSE,ylab = "log2 Intensities")
```

```{r eval=(plots == "LIMMA"), echo=(plots == "LIMMA")}

  path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
  setwd(path)

png(filename = file.path(path,"normBoxplot.png"), width = 1000, height = 1000)
  par(mar=c(30,5,5,5))
boxplot(data.frame(log2(as.matrix(data))),main="Normalized Data Log2 Intensities", las=2,outline=FALSE)
invisible(dev.off())
  
boxplot(data.frame(log2(as.matrix(data))),main="Normalized Data Log2 Intensities", las=2,outline=FALSE)

```
## Normalized PCA Plot
```{r}
  path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
  setwd(path)
########## Create Normalized PCA Plots
library(ggplot2)
try(exp_raw <- log2(as.matrix(data)))
try(exp_raw <- log2(exprs(data)))
PCA_raw <- prcomp(t(exp_raw), scale. = FALSE)

percentVar <- round(100*PCA_raw$sdev^2/sum(PCA_raw$sdev^2),1)
sd_ratio <- sqrt(percentVar[2] / percentVar[1])

dataGG <- data.frame(PC1 = PCA_raw$x[,1], PC2 = PCA_raw$x[,2], Group = targets$t1$Group)

PCA_plot <- ggplot(dataGG, aes(PC1, PC2)) +
      geom_point(aes(colour = Group)) +
  ggtitle("Normalized Data PCA Plot of log2 Expression") +
  xlab(paste0("PC1, VarExp: ", percentVar[1], "%")) +
  ylab(paste0("PC2, VarExp: ", percentVar[2], "%"))
png(filename = file.path(path,"normPCA.png"))
plot(PCA_plot)
invisible(dev.off())
plot(PCA_plot)
rm(PCA_plot,PCA_raw,exp_raw,dataGG,path,sd_ratio,percentVar)
```

```{r, eval=(opt$estimation == "Max IQR"),echo=(opt$estimation == "Max IQR")}
### Gene level estimation by maximum interquartile range
data.filt <- data
try({data.filt <- genefilter::nsFilter(data, require.entrez=(opt$filter_nonannotated == TRUE),
    remove.dupEntrez=TRUE, var.func=IQR,
    var.cutoff=0.5, var.filter=TRUE,
    filterByQuantile=TRUE, feature.exclude="^AFFX")
cat("Probe Aggregation Summary \n")
str(data.filt$filter.log)
data.filt <- data.filt$eset
annotation_stats$gene_level_features <-dim(data.filt@featureData@data)[1]})


```

```{r, eval=(opt$estimation == "kNN"),echo=(opt$estimation == "kNN")}
### Gene level estimation by k nearest neighbors
data.filt <- knnCV(exprs(data))


```

```{r eval=(opt$model == "Group Contrast"), echo=(opt$model == "Group Contrast")}

### Basic linear model fit
library(limma)


group__ <- factor(targets$t3$Group, levels = unique(targets$t3$Group))
design <- model.matrix(~ 0 + group__)
colnames(design)<-gsub("group__","",colnames(design)) #remove design name formatting
fit <- lmFit(data.filt, design)
  
if (is.fullrank(design) == FALSE){
  cat("The following groups are non estimable:",nonEstimable(design))
}

fit.groups <- colnames(fit$design)[which(fit$assign == 1)]
fit.index <-  which(levels(group__) %in% fit.groups)
fit.group.names <- levels(factor(targets$t2$Group))[fit.index]

```

```{r eval=(opt$model == "Repeated Measures"),echo=(opt$model == "Repeated Measures")}

### Repeated measures fit
library(limma)
source__ <- factor(targets$t3$SourceName, levels = unique(targets$t3$SourceName))
group__ <- factor(targets$t3$Group, levels = unique(targets$t3$Group))
design <- model.matrix(~source__+group__)
# colnames(design)<-gsub("source__","",colnames(design)) #remove design name formatting
# colnames(design)<-gsub("group__","",colnames(design)) #remove design name formatting

# dupfit <- duplicateCorrelation(data.filt, design, ndups=1, block=source__)
# fit <- lmFit(data.filt, design, correlation=dupfit$consensus, block=source__)

fit <- lmFit(data.filt, design)
nonestimable <- nonEstimable(design)
  
# if (is.fullrank(design) == FALSE){
#   nonestimable <- nonEstimable(design)
#   nonestimable_samples <- which(targets$t3$Group == nonestimable)
#   cat("The following groups are non estimable: \n",nonestimable, "\n")
#   data.filt <- data.filt[,-c(nonestimable_samples)]
#   targets$t2 <- targets$t2[-c(nonestimable_samples),]
#   targets$t3 <- targets$t3[-c(nonestimable_samples),]
#   source__ <- factor(targets$t3$SourceName, levels = unique(targets$t3$SourceName))
#   group__ <- factor(targets$t3$Group, levels = unique(targets$t3$Group))
#   design <- model.matrix(~ 0 + source__ + group__)
#   colnames(design)<-gsub("source__","",colnames(design)) #remove design name formatting
#   colnames(design)<-gsub("group__","",colnames(design)) #remove design name formatting
#   fit <- lmFit(data.filt, design)
# }

if (length(which(fit$assign == 2)) != length(levels(group__))){ #if not all groups are fit
  cat("Not all factor groups could be modeled in paired design: Partial NA coefficients")
}
  
fit.groups <- colnames(fit$design)[which(fit$assign == 2)]
fit.index <-  which(levels(group__) %in% fit.groups)
fit.group.names <- levels(factor(targets$t2$Group))[fit.index]

```

```{r eval=(opt$filter_nonexpressed), echo=(opt$filter_nonexpressed), message=FALSE, warning=FALSE}

CutOff <- quantile(as.matrix(data),probs=.33)

hist_res <- graphics::hist(as.matrix(data.filt), 100, col = "cornsilk", freq = FALSE, 
            main = "Probe Filtering Intensity Cutoff",
            border = "antiquewhite4",
            xlab = "Median intensities")

abline(v = CutOff, col = "coral4", lwd = 2)

keep <- fit$Amean > CutOff
fit <- fit[keep,] # filter out probes below cutoff expression level

# remove <- ftable$ID[is.na(ftable$Gene.ID)]
# '%!in%' <- function(x,y)!('%in%'(x,y))
# keep <- rownames(fit) %!in% remove
# fit <- fit[keep,] # filter out unannotated probes
annotation_stats$expressed_genes <- dim(fit$genes)[1]
path <- file.path(workdir,"Processed_Data",opt$glds,"01-NormalizedData","QC_Repports")
setwd(path)
write.table(annotation_stats,file = "annotReport.txt", quote = FALSE)
rm(hist_res,keep,CutOff,path)
```

```{r}
### Create Contrast Model
combos<-combn(fit.groups,2) # generate matrix of pairwise group combinations for comparison
combos.names<-combn(fit.group.names,2)
contrasts<-c(paste(combos[1,],combos[2,],sep = "-"),paste(combos[2,],combos[1,],sep = "-")) # format combinations for limma:makeContrasts
contrast.names <-c(paste(combos.names[1,],combos.names[2,],sep = "v"),paste(combos.names[2,],combos.names[1,],sep = "v")) # format combinations for output table file names
  
  
cont.matrix <- makeContrasts(contrasts = contrasts,levels=design)

contrast.fit <- contrasts.fit(fit, cont.matrix)
contrast.fit <- eBayes(contrast.fit)
results<-decideTests(contrast.fit, method = "separate", adjust.method = "BH", p.value = 0.05, lfc = 0.5) # FDR .05
try({
  colnames(results@.Data) <- contrast.names
  summary <- as.data.frame(summary(results))
  summary <- summary[,c(2,1,3)]
  colnames(summary)<-c("CONTRAST","REGULATION","GENE COUNT SIG")
  DT::datatable(summary, caption = "Summary of Differentially Regulated Genes (P<=05)")
})
rm(combos,combos.names,cont.matrix)
```

```{r}
########## Construct DGE Output Tables

dir.create(file.path(workdir,"Processed_Data",opt$glds,"02-Limma_DGE"), showWarnings = FALSE)
setwd(file.path(workdir,"Processed_Data",opt$glds,"02-Limma_DGE"))

output_table <- fit$genes
reduced_output_table <- fit$genes

# add all sample mean column
output_table$All.mean <- fit$Amean
reduced_output_table$All.mean <- fit$Amean
# add all sample stdev column
output_table$All.stdev <- fit$s2.post
reduced_output_table$All.stdev <- fit$s2.post
# add F statistic p-value (similar to ANOVA p-value) column
output_table$F.p.value <- fit$F.p.value
reduced_output_table$F.p.value <- fit$F.p.value

uu<- unique(targets$t2$Group)

########## Add Group Mean Valies
group_means<-fit$coefficients
colnames(group_means)<-paste0("Group.Mean_",uu)
output_table<-cbind(output_table,group_means)
reduced_output_table<-cbind(reduced_output_table,group_means)
rm(group_means)

# add group stdev columns
group_stdev<-fit$stdev.unscaled * fit$coefficients
colnames(group_stdev)<-paste0("Group.Stdev_",uu)
output_table<-cbind(output_table,group_stdev)
reduced_output_table<-cbind(reduced_output_table,group_stdev)
rm(group_stdev)

# iterate through contrasts
for (i in 1:length(contrasts)){
  top <- topTable(contrast.fit, coef = i, number = Inf, genelist = contrast.fit$genes$ID, adjust.method = "BH", sort.by = "none")
  table <- top[,c(1,4,5)] # Pull columns for Log2fc, P.value, Adj.p.value
  colnames(table)<- c("Log2fc","P.value","Adj.p.value")
  table.reduced <- table
  table$Updown <- sign(top$logFC)
  table$Sig.1 <- top$adj.P.Val<=0.1
  table$Sig.05 <- top$adj.P.Val<=0.05
  table$Log2_P.value <- log2(top$P.Value) # For volcano plot
  table$Log2_Adj.p.value <- log2(top$adj.P.Val) # For volcano plot
  
  colnames(table.reduced)<-paste(colnames(table.reduced),contrast.names[i],sep = "_")
  colnames(table)<-paste(colnames(table),contrast.names[i],sep = "_")
  output_table<-cbind(output_table,table)
  reduced_output_table<-cbind(reduced_output_table,table.reduced)
  }
#rm(i,top,table,table.reduced)

# Export DGE Output Data Tables
write.csv(reduced_output_table,"differential_expression.csv", row.names = FALSE)
write.csv(output_table,"visualization_output_table.csv", row.names = FALSE)
contrast.output <- contrast.fit$contrasts
row.names(contrast.output)<-uu
colnames(contrast.output)<-contrast.names
write.csv(contrast.output,"contrasts.csv")

rm (uu,group__,fit.index,fit.groups,fit.group.names,contrasts,contrast.names,targets3,targets2)
```

```{r include=FALSE}
### Move metadata files
dir.create(file.path(workdir,"Processed_Data",opt$glds,"Metadata"), showWarnings = FALSE)
path <- file.path(workdir,"Processed_Data",opt$glds,"Metadata")
file.copy(from = opt[["isafile"]][["datapath"]], to = file.path(path,"ISA.zip"), overwrite = FALSE, recursive = FALSE, copy.mode = FALSE)

file.copy(from = opt[["probefile"]][["datapath"]], to = file.path(path,opt[["probefile"]][["name"]]), overwrite = FALSE, recursive = FALSE, copy.mode = FALSE)
rm(path)
```

```{r}
sessionInfo()
```

