image: nfcore/gitpod:latest

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - GitHub.copilot
    - REditorSupport.r
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
