process REMOVE_RRNA_FEATURECOUNTS {
    /**
     * Filters a featureCounts output file by removing rRNA gene IDs
     * and counts the number of rRNA genes removed for each sample
     *
     * Inputs:
     *   counts_file: Path to the input featureCounts output file.
     *   rrna_ids_file: Path to the file containing rRNA IDs (generated by `EXTRACT_RRNA`).
     *
     * Outputs:
     *   Filtered featureCounts output file (rRNA removed).
     *   rRNA count summary file containing the number of rRNA genes removed for each sample.
     */

    tag "${counts.simpleName}"

    input:
        path(counts)
        path(rrna_ids)

    output:
        path("filtered_counts.tsv"), emit: counts_rrnarm
        path("rRNA_counts.txt"), emit: summary

    script:
        """
        python $projectDir/bin/remove_rrna_featurecounts.py ${counts} ${rrna_ids} filtered_counts.tsv
        """
}