name: CI Updated Modules Testing
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - DEV_NF_RCP-F

env:
  NXF_ANSI_LOG: false

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'modules' output variable
      modules: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'DEV_NF_RCP-F'
          filters: "RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/tests/config/nftest_modules.yml"

  test:
    name: ${{ matrix.tags }} ${{ matrix.profile }} ${{ matrix.NXF_VER }}
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.modules != '[]'
    strategy:
      matrix:
        NXF_VER:
          - "22.10.1"
          - "latest-everything"
        profile:
          - "docker"
          - "singularity"
        tags: ["${{ fromJson(needs.changes.outputs.modules) }}"]

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@be72b1dc0f932cea69aef64479ac863a86516c0c
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.7.1

      - name: Install nf-test
        id: nf-test
        run: |
          curl -fsSL https://code.askimed.com/install/nf-test | bash
          chmod u+x nf-test
          echo "bin_path=$(pwd)/nf-test" >> $GITHUB_OUTPUT
          

      - name: Hash Github Workspace
        id: hash_workspace
        run: |
          echo "digest=$(echo RNA_3.10.1_${{ github.workspace }} | md5sum | cut -c 1-25)" >> $GITHUB_OUTPUT

      - name: Cache test data
        id: cache-testdata
        uses: actions/cache@v3
        with:
          path: RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/test-datasets
          key: ${{ steps.hash_workspace.outputs.digest }}

      - name: Check out test data
        if: steps.cache-testdata.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: J-81/test-datasets-extended
          ref: NF_RCP-F
          path: RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/test-datasets

      # Test the module
      - name: Run nf-test
        run: |
          cd ${GITHUB_WORKSPACE}/RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/
          ${{ steps.nf-test.outputs.bin_path}} test \
            --profile=${{ matrix.profile }} \
            --tag ${{ matrix.tags }} \
            --tap=test.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            ${GITHUB_WORKSPACE}/RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/test.tap