name: Check Markdown links

on:
  create: # runs when a reference (branch or tag) is created
      
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
